plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.1'
}

group 'com.blitzoffline'
version '1.0.0'

repositories {
    mavenCentral()
    maven { url = "https://repo.helpch.at/releases/" }
    maven { url = "https://repo.codemc.io/repository/hytale/" }
}

dependencies {
    compileOnly 'org.jetbrains:annotations:24.1.0'

    compileOnly 'at.helpch:placeholderapi-hytale:1.0.4'
    compileOnly("com.hypixel.hytale:Server:2026.01.17-4b0f30090")
}

compileJava.options.encoding = 'UTF-8'

shadowJar {
    archiveFileName.set("StringExpansion-${project.version}.jar")
}